### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by niftylettuce** [twada/gulp-unassert#4]
Just sharing here, as soon as I disable `gulp-unassert`, my build completes successfully.

At the top of a file, I include this, and the error just started after doing so:

```js
require('core-js/stable');
require('regenerator-runtime/runtime');
```

Output:

```sh
events.js:288
      throw er; // Unhandled 'error' event
      ^
PluginError [SyntaxError]: Unexpected token (8068:5)
    at Parser.pp$4.raise (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp.expect (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:641:26)
    at Parser.pp$3.parseObj (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2376:14)
    at Parser.pp$3.parseExprAtom (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2179:17)
    at Parser.pp$3.parseExprSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseExprList (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2663:20)
    at Parser.pp$3.parseSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1949:19)
Emitted 'error' event on Domain instance at:
    at DestroyableTransform.EventEmitter.emit (domain.js:500:12)
    at DestroyableTransform.onerror (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:311:20)
    at DestroyableTransform.EventEmitter.emit (domain.js:482:12)
    at onwriteError (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:443:12)
    at onwrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:93:3)
    at DestroyableTransform._transform (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/index.js:96:24)
    at DestroyableTransform.Transform._read (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:311:20) {
  pos: 271748,
  loc: Position { line: 8068, column: 5 },
  raisedAt: 271748,
  message: 'Unexpected token (8068:5)',
  name: 'SyntaxError',
  stack: 'SyntaxError: Unexpected token (8068:5)\n' +
    '    at Parser.pp$4.raise (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2757:13)\n' +
    '    at Parser.pp.unexpected (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:647:8)\n' +
    '    at Parser.pp.expect (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:641:26)\n' +
    '    at Parser.pp$3.parseObj (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2376:14)\n' +
    '    at Parser.pp$3.parseExprAtom (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2179:17)\n' +
    '    at Parser.pp$3.parseExprSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2047:19)\n' +
    '    at Parser.pp$3.parseMaybeUnary (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2024:17)\n' +
    '    at Parser.pp$3.parseExprOps (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1966:19)\n' +
    '    at Parser.pp$3.parseMaybeConditional (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1949:19)\n' +
    '    at Parser.pp$3.parseMaybeAssign (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1925:19)\n' +
    '    at Parser.pp$3.parseExprList (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2663:20)\n' +
    '    at Parser.pp$3.parseSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2075:29)\n' +
    '    at Parser.pp$3.parseExprSubscripts (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2050:21)\n' +
    '    at Parser.pp$3.parseMaybeUnary (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:2024:17)\n' +
    '    at Parser.pp$3.parseExprOps (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1966:19)\n' +
    '    at Parser.pp$3.parseMaybeConditional (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/node_modules/acorn/dist/acorn.js:1949:19)\n' +
    "Emitted 'error' event on Domain instance at:\n" +
    '    at DestroyableTransform.EventEmitter.emit (domain.js:500:12)\n' +
    '    at DestroyableTransform.onerror (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_readable.js:640:52)\n' +
    '    at DestroyableTransform.emit (events.js:311:20)\n' +
    '    at DestroyableTransform.EventEmitter.emit (domain.js:482:12)\n' +
    '    at onwriteError (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:443:12)\n' +
    '    at onwrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:470:11)\n' +
    '    at WritableState.onwrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:180:5)\n' +
    '    at DestroyableTransform.afterTransform (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:93:3)\n' +
    '    at DestroyableTransform._transform (/Users/user/Projects/lad.sh/node_modules/gulp-unassert/index.js:96:24)\n' +
    '    at DestroyableTransform.Transform._read (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n' +
    '    at DestroyableTransform.Transform._write (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n' +
    '    at doWrite (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:428:64)\n' +
    '    at writeOrBuffer (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:417:5)\n' +
    '    at DestroyableTransform.Writable.write (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_writable.js:334:11)\n' +
    '    at DestroyableTransform.ondata (/Users/user/Projects/lad.sh/node_modules/readable-stream/lib/_stream_readable.js:619:20)\n' +
    '    at DestroyableTransform.emit (events.js:311:20)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-unassert',
  showProperties: true,
  showStack: true,
  domainEmitter: DestroyableTransform {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [DestroyableTransform],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      prefinish: [Function: prefinish],
      data: [Function: ondata]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: true,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'utf8'
    },
    _destroyed: false,
    _transform: [Function],
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
```

Node version: v12.16.1
Package version: 1.1.0

**Comment by twada** [comment]
@niftylettuce Thank you for reporting.

However I'm struggling with creating reproduction case because
```js
require('core-js/stable');
require('regenerator-runtime/runtime');
```
is syntactically correct, so given input:

```js
require('core-js/stable');
require('regenerator-runtime/runtime');

const assert = require('assert');

function add (a, b) {
    assert(!(isNaN(a) || isNaN(a)));
    return a + b;
}
```
works as expected:
```js
require('core-js/stable');
require('regenerator-runtime/runtime');
function add(a, b) {
    return a + b;
}
```
Would you give me a small repro case?

**Comment by niftylettuce** [comment]
I was using browserify/bundler, and resolved issue on my own, thanks!

**Comment by twada** [comment]
@niftylettuce Glad to hear!
